[package]
name = "chatapp"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chatlib = { path = "../chatlib" }
crossbeam = "0.8.4"
crossterm = "0.28.1"
serde = { version = "1.0.210", features = ["derive"] }
tui = "0.19.0"
